// Frame class created by David McCann
// Student Number: 12431298
// Class used to represent a Frame of tiles used in Scrabble.

class Frame{
	
	// Variables initialised.
	int total;
	final int BIG = 100, frameNumber = 7;
	// Initialise pool object from pool class.
	Pool pool = new Pool();
	// Create Tile array to store Tiles.
	Tile[] tileArray = new Tile[BIG];
	
	// Constructs the Frame with 7 tiles.
	public Frame(){
		total = 0;
		for (int i = 0; i < frameNumber; i++) {
			tileArray[i] = pool.drawTileFromPool();
			total++;
		}
	}
	
	// Method to get the value of the tile generated by its number in the Frame.
	public int getValue(int tileNumber){
		return tileArray[tileNumber - 1].getValue();
	}
	
	// Method to print all tiles in the frame. 
	public String printTiles(){
		String print = "";
		for (int i = 0; i < frameNumber; i++) {
			print += "Tile " + (i + 1) + ": " + tileArray[i] + "\n";
		}
		return print;
	}
	
	// Gets the size of the frame and returns it.
	public int size(){
		return total;
	}
	
	//  Replaces any tiles that have been removed with another Tile.
	public void replaceTiles(){
		for (int i = 0; i < frameNumber; i++) {
			if (tileArray[i].getLetter() == '0') {
				tileArray[i] = pool.drawTileFromPool();
			}
		}
	}
	
	// Completely refill Frame with 7 new Tiles.
	public void reFill(){
		total = 0;
		for (int i = 0; i < frameNumber; i++) {
			tileArray[i] =  pool.drawTileFromPool();
			total++;
		}
	}
	
	// Removes a chosen tile from the Frame.
	public void removeTile(int tileNumber){
				tileArray[tileNumber - 1] = new Tile();
				total--;
	}
	
	// Checks whether a chosen letter is in the Frame.
	public boolean letterCheck(char letter){
		boolean check = false;
		for (int i = 0; i < frameNumber; i++) {
			if (tileArray[i].getLetter() == letter) {
				check = true;
			}
		}
		return check;
	}
	
	// Checks whether the frame is empty or not.
	public Boolean isEmpty(){
		return total == 0;
	}
}